package com.qimi.app.qplayer.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF65558F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE9DDFF)
val onPrimaryContainerLight = Color(0xFF201047)
val secondaryLight = Color(0xFF65558F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE9DDFF)
val onSecondaryContainerLight = Color(0xFF210F47)
val tertiaryLight = Color(0xFF8B4A61)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E3)
val onTertiaryContainerLight = Color(0xFF3A071E)
val errorLight = Color(0xFF904A42)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD5)
val onErrorContainerLight = Color(0xFF3B0906)
val backgroundLight = Color(0xFFFDF7FF)
val onBackgroundLight = Color(0xFF1D1B20)
val surfaceLight = Color(0xFFFEF7FF)
val onSurfaceLight = Color(0xFF1D1B20)
val surfaceVariantLight = Color(0xFFE7E0EB)
val onSurfaceVariantLight = Color(0xFF49454E)
val outlineLight = Color(0xFF7A757F)
val outlineVariantLight = Color(0xFFCAC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFFCFBDFE)
val surfaceDimLight = Color(0xFFDED8E0)
val surfaceBrightLight = Color(0xFFFEF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F1FA)
val surfaceContainerLight = Color(0xFFF2ECF4)
val surfaceContainerHighLight = Color(0xFFEDE6EE)
val surfaceContainerHighestLight = Color(0xFFE7E0E8)

val primaryDark = Color(0xFFCFBDFE)
val onPrimaryDark = Color(0xFF36275D)
val primaryContainerDark = Color(0xFF4D3D75)
val onPrimaryContainerDark = Color(0xFFE9DDFF)
val secondaryDark = Color(0xFFD0BCFE)
val onSecondaryDark = Color(0xFF36265D)
val secondaryContainerDark = Color(0xFF4D3D75)
val onSecondaryContainerDark = Color(0xFFE9DDFF)
val tertiaryDark = Color(0xFFFFB0CA)
val onTertiaryDark = Color(0xFF541D33)
val tertiaryContainerDark = Color(0xFF6F334A)
val onTertiaryContainerDark = Color(0xFFFFD9E3)
val errorDark = Color(0xFFFFB4AA)
val onErrorDark = Color(0xFF561E18)
val errorContainerDark = Color(0xFF73342C)
val onErrorContainerDark = Color(0xFFFFDAD5)
val backgroundDark = Color(0xFF141218)
val onBackgroundDark = Color(0xFFE6E0E9)
val surfaceDark = Color(0xFF151218)
val onSurfaceDark = Color(0xFFE7E0E8)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFCAC4CF)
val outlineDark = Color(0xFF948F99)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E0E8)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF65558F)
val surfaceDimDark = Color(0xFF151218)
val surfaceBrightDark = Color(0xFF3B383E)
val surfaceContainerLowestDark = Color(0xFF0F0D13)
val surfaceContainerLowDark = Color(0xFF1D1B20)
val surfaceContainerDark = Color(0xFF211F24)
val surfaceContainerHighDark = Color(0xFF2C292F)
val surfaceContainerHighestDark = Color(0xFF37343A)




